services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: supersecret
      MYSQL_DATABASE: ghost
      MYSQL_USER: ghost
      MYSQL_PASSWORD: ghost
    volumes:
      - mysql_data1:/var/lib/mysql
    healthcheck:
      test:
        [
          'CMD',
          'mysqladmin',
          'ping',
          '-h',
          '127.0.0.1',
          '-u',
          'ghost',
          '-pghost',
        ]
      interval: 5s
      timeout: 3s
      retries: 20

  ghost:
    image: ghost:5-alpine
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '2368:2368'
    environment:
      url: http://localhost:2368
      database__client: mysql
      database__connection__host: db
      database__connection__user: ghost
      database__connection__password: ghost
      database__connection__database: ghost
    volumes:
      - ghost_content:/var/lib/ghost/content

volumes:
  mysql_data1:
  ghost_content:
